import * as db from "../db";
import { TRPCError } from "@trpc/server";
import { orgScopedProcedure, router } from "../_core/trpc";
import { z } from "zod";

export const tasksRouter = router({
  list: orgScopedProcedure
    .input(
      z.object({
        status: z.enum(["open", "in_progress", "completed"]).optional(),
        assignedTo: z.number().optional(),
        assignedName: z.string().optional(),
        meetingId: z.number().optional(),
        category: z.string().optional(),
      }).optional()
    )
    .query(async ({ input, ctx }) => {
      return await db.getAllTasks(input ? { ...input, orgId: ctx.orgId ?? undefined } : { orgId: ctx.orgId ?? undefined });
    }),

  getById: orgScopedProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ ctx, input }) => {
      const task = await db.getTaskById(input.id);
      if (!task) throw new TRPCError({ code: "NOT_FOUND", message: "Task not found" });
      return task;
    }),

  categories: orgScopedProcedure.query(async ({ ctx }) => {
    return await db.getTaskCategories(ctx.orgId ?? undefined);
  }),

  assignees: orgScopedProcedure.query(async ({ ctx }) => {
    return await db.getTaskAssignees(ctx.orgId ?? undefined);
  }),

  create: orgScopedProcedure
    .input(
      z.object({
        title: z.string().min(1).max(500),
        description: z.string().optional(),
        priority: z.enum(["low", "medium", "high"]).default("medium"),
        assignedTo: z.number().optional(),
        assignedName: z.string().optional(),
        meetingId: z.number().optional(),
        dueDate: z.string().optional(),
        category: z.string().optional(),
        notes: z.string().optional(),
        isAutoGenerated: z.boolean().default(false),
      })
    )
    .mutation(async ({ input, ctx }) => {
      const taskData = {
        title: input.title,
        description: input.description ?? null,
        priority: input.priority,
        assignedTo: input.assignedTo ?? null,
        assignedName: input.assignedName ?? null,
        meetingId: input.meetingId ?? null,
        dueDate: input.dueDate ? new Date(input.dueDate) : null,
        category: input.category ?? null,
        notes: input.notes ?? null,
        isAutoGenerated: input.isAutoGenerated,
        createdBy: ctx.user.id,
      };
      const taskId = await db.createTask(taskData);
      return { id: taskId };
    }),

  update: orgScopedProcedure
    .input(
      z.object({
        id: z.number(),
        title: z.string().min(1).max(500).optional(),
        description: z.string().nullable().optional(),
        priority: z.enum(["low", "medium", "high"]).optional(),
        status: z.enum(["open", "in_progress", "completed"]).optional(),
        assignedTo: z.number().nullable().optional(),
        assignedName: z.string().nullable().optional(),
        dueDate: z.string().nullable().optional(),
        category: z.string().nullable().optional(),
        notes: z.string().nullable().optional(),
      })
    )
    .mutation(async ({ input }) => {
      const updates: any = {};
      if (input.title) updates.title = input.title;
      if (input.description !== undefined) updates.description = input.description;
      if (input.priority) updates.priority = input.priority;
      if (input.status) updates.status = input.status;
      if (input.assignedTo !== undefined) updates.assignedTo = input.assignedTo;
      if (input.assignedName !== undefined) updates.assignedName = input.assignedName;
      if (input.dueDate !== undefined) {
        updates.dueDate = input.dueDate ? new Date(input.dueDate) : null;
      }
      if (input.category !== undefined) updates.category = input.category;
      if (input.notes !== undefined) updates.notes = input.notes;
      await db.updateTask(input.id, updates);
      return { success: true };
    }),

  delete: orgScopedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input }) => {
      await db.deleteTask(input.id);
      return { success: true };
    }),

  bulkDelete: orgScopedProcedure
    .input(z.object({ ids: z.array(z.number()).min(1) }))
    .mutation(async ({ input }) => {
      for (const id of input.ids) {
        await db.deleteTask(id);
      }
      return { success: true, deleted: input.ids.length };
    }),

  bulkUpdate: orgScopedProcedure
    .input(z.object({
      ids: z.array(z.number()).min(1),
      updates: z.object({
        category: z.string().optional(),
        assignedName: z.string().optional(),
        status: z.enum(["open", "in_progress", "completed"]).optional(),
        priority: z.enum(["low", "medium", "high"]).optional(),
        dueDate: z.string().optional(),
      }),
    }))
    .mutation(async ({ input }) => {
      const updates: any = {};
      if (input.updates.category !== undefined) updates.category = input.updates.category || null;
      if (input.updates.assignedName !== undefined) updates.assignedName = input.updates.assignedName || null;
      if (input.updates.status !== undefined) updates.status = input.updates.status;
      if (input.updates.priority !== undefined) updates.priority = input.updates.priority;
      if (input.updates.dueDate !== undefined) updates.dueDate = input.updates.dueDate ? new Date(input.updates.dueDate) : null;
      for (const id of input.ids) {
        await db.updateTask(id, updates);
      }
      return { success: true, updated: input.ids.length };
    }),
});
