import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, index } from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Meetings table - stores all call intelligence reports
 */
export const meetings = mysqlTable("meetings", {
  id: int("id").autoincrement().primaryKey(),
  
  // Metadata
  meetingDate: timestamp("meetingDate").notNull(),
  primaryLead: varchar("primaryLead", { length: 255 }).notNull(), // Junaid, Kyle, etc.
  participants: text("participants").notNull(), // JSON array of participant names
  organizations: text("organizations"), // JSON array of organization names
  jurisdictions: text("jurisdictions"), // JSON array of jurisdictions (UAE, USA, GCC, etc.)
  
  // Intelligence Content
  executiveSummary: text("executiveSummary").notNull(),
  strategicHighlights: text("strategicHighlights"), // JSON array of highlights
  opportunities: text("opportunities"), // JSON array of opportunities
  risks: text("risks"), // JSON array of risks/red flags
  keyQuotes: text("keyQuotes"), // JSON array of quotes
  intelligenceData: text("intelligenceData"), // JSON object with dollar amounts, percentages, etc.
  
  // Full transcript for search
  fullTranscript: text("fullTranscript"),
  
  // Source tracking
  sourceType: mysqlEnum("sourceType", ["plaud", "fathom", "manual"]).notNull(),
  sourceId: varchar("sourceId", { length: 255 }), // External ID from Plaud/Fathom
  
  // Generated branded report
  brandedReportUrl: text("brandedReportUrl"), // URL to auto-generated OmniScope-branded PDF report
  
  // Timestamps
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdBy: int("createdBy").references(() => users.id),
}, (table) => ({
  meetingDateIdx: index("meeting_date_idx").on(table.meetingDate),
  primaryLeadIdx: index("primary_lead_idx").on(table.primaryLead),
  sourceIdIdx: index("source_id_idx").on(table.sourceId),
}));

export type Meeting = typeof meetings.$inferSelect;
export type InsertMeeting = typeof meetings.$inferInsert;

/**
 * Tags table - sectors and jurisdictions for categorization
 */
export const tags = mysqlTable("tags", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  type: mysqlEnum("type", ["sector", "jurisdiction"]).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, (table) => ({
  typeIdx: index("type_idx").on(table.type),
}));

export type Tag = typeof tags.$inferSelect;
export type InsertTag = typeof tags.$inferInsert;

/**
 * Meeting tags junction table
 */
export const meetingTags = mysqlTable("meeting_tags", {
  id: int("id").autoincrement().primaryKey(),
  meetingId: int("meetingId").notNull().references(() => meetings.id, { onDelete: "cascade" }),
  tagId: int("tagId").notNull().references(() => tags.id, { onDelete: "cascade" }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
}, (table) => ({
  meetingIdIdx: index("meeting_id_idx").on(table.meetingId),
  tagIdIdx: index("tag_id_idx").on(table.tagId),
}));

export type MeetingTag = typeof meetingTags.$inferSelect;
export type InsertMeetingTag = typeof meetingTags.$inferInsert;

/**
 * Tasks table - action items from meetings or manually created
 */
export const tasks = mysqlTable("tasks", {
  id: int("id").autoincrement().primaryKey(),
  
  // Task details
  title: varchar("title", { length: 500 }).notNull(),
  description: text("description"),
  priority: mysqlEnum("priority", ["low", "medium", "high"]).default("medium").notNull(),
  status: mysqlEnum("status", ["open", "in_progress", "completed"]).default("open").notNull(),
  
  // Assignment
  assignedTo: int("assignedTo").references(() => users.id),
  
  // Source tracking
  meetingId: int("meetingId").references(() => meetings.id, { onDelete: "set null" }),
  isAutoGenerated: boolean("isAutoGenerated").default(false).notNull(),
  
  // Timeline
  dueDate: timestamp("dueDate"),
  completedAt: timestamp("completedAt"),
  
  // Timestamps
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdBy: int("createdBy").references(() => users.id),
}, (table) => ({
  statusIdx: index("status_idx").on(table.status),
  assignedToIdx: index("assigned_to_idx").on(table.assignedTo),
  meetingIdIdx: index("meeting_id_idx").on(table.meetingId),
}));

export type Task = typeof tasks.$inferSelect;
export type InsertTask = typeof tasks.$inferInsert;

/**
 * Relations
 */
export const meetingsRelations = relations(meetings, ({ many, one }) => ({
  tags: many(meetingTags),
  tasks: many(tasks),
  creator: one(users, {
    fields: [meetings.createdBy],
    references: [users.id],
  }),
}));

export const tagsRelations = relations(tags, ({ many }) => ({
  meetings: many(meetingTags),
}));

export const meetingTagsRelations = relations(meetingTags, ({ one }) => ({
  meeting: one(meetings, {
    fields: [meetingTags.meetingId],
    references: [meetings.id],
  }),
  tag: one(tags, {
    fields: [meetingTags.tagId],
    references: [tags.id],
  }),
}));

export const tasksRelations = relations(tasks, ({ one }) => ({
  meeting: one(meetings, {
    fields: [tasks.meetingId],
    references: [meetings.id],
  }),
  assignee: one(users, {
    fields: [tasks.assignedTo],
    references: [users.id],
  }),
  creator: one(users, {
    fields: [tasks.createdBy],
    references: [users.id],
  }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  createdMeetings: many(meetings),
  assignedTasks: many(tasks),
}));
