import * as analytics from "./analytics";

export interface ExportedReport {
  filename: string;
  content: string;
  mimeType: string;
}

/**
 * Export daily summary as Markdown
 */
export async function exportDailySummaryMarkdown(date: Date, orgId?: number | null): Promise<ExportedReport> {
  const summary = await analytics.getDailySummary(date, orgId);
  
  const dateStr = new Date(summary.date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const content = `
# OmniScope Daily Intelligence Report
**${dateStr}**

---

## Overview

- **Meetings:** ${summary.meetingCount}
- **Tasks Created:** ${summary.tasksCreated}
- **Tasks Completed:** ${summary.tasksCompleted}

## Active Sectors

${summary.topSectors.length > 0 ? summary.topSectors.map(s => `- ${s}`).join('\n') : '_No sector data available_'}

## Jurisdictions

${summary.topJurisdictions.length > 0 ? summary.topJurisdictions.map(j => `- ${j}`).join('\n') : '_No jurisdiction data available_'}

---

## Meeting Summaries

${summary.meetings.length > 0 ? summary.meetings.map(m => `
### ${m.participants.join(', ')} - ${m.time}

${m.organizations.length > 0 ? `**Organizations:** ${m.organizations.join(', ')}\n\n` : ''}**Summary:** ${m.summary}

${m.keyHighlights.length > 0 ? `**Key Highlights:**\n${m.keyHighlights.map(h => `- ${h}`).join('\n')}` : ''}

---
`).join('\n') : '_No meetings recorded today._'}

---

*Generated by OmniScope Intelligence Portal*  
*All Markets. One Scope.*
  `.trim();

  const filename = `omniscope-daily-${new Date(summary.date).toISOString().split('T')[0]}.md`;

  return {
    filename,
    content,
    mimeType: 'text/markdown',
  };
}

/**
 * Export weekly summary as Markdown
 */
export async function exportWeeklySummaryMarkdown(weekStart: Date, orgId?: number | null): Promise<ExportedReport> {
  const summary = await analytics.getWeeklySummary(weekStart, orgId);
  
  const weekStartStr = new Date(summary.weekStart).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });
  
  const weekEndStr = new Date(summary.weekEnd).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  const content = `
# OmniScope Weekly Intelligence Report
**Week of ${weekStartStr} - ${weekEndStr}**

---

## Executive Summary

- **Total Meetings:** ${summary.meetingCount}
- **Unique Participants:** ${summary.uniqueParticipants}
- **Unique Organizations:** ${summary.uniqueOrganizations}
- **Tasks Created:** ${summary.tasksCreated}
- **Tasks Completed:** ${summary.tasksCompleted}

---

## Top Sectors

${summary.topSectors.length > 0 ? summary.topSectors.map(s => `- **${s.sector}:** ${s.count} meetings`).join('\n') : '_No sector data available_'}

## Top Jurisdictions

${summary.topJurisdictions.length > 0 ? summary.topJurisdictions.map(j => `- **${j.jurisdiction}:** ${j.count} meetings`).join('\n') : '_No jurisdiction data available_'}

---

## Daily Breakdown

| Date | Meetings |
|------|----------|
${summary.dailyBreakdown.map(d => {
  const date = new Date(d.date).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
  return `| ${date} | ${d.meetingCount} |`;
}).join('\n')}

---

## Key Opportunities

${summary.keyOpportunities.length > 0 ? summary.keyOpportunities.map((o, i) => `${i + 1}. ${o}`).join('\n') : '_No opportunities recorded this week._'}

---

## Risk Considerations

${summary.keyRisks.length > 0 ? summary.keyRisks.map((r, i) => `${i + 1}. ${r}`).join('\n') : '_No risks recorded this week._'}

---

*Generated by OmniScope Intelligence Portal*  
*All Markets. One Scope.*
  `.trim();

  const filename = `omniscope-weekly-${new Date(summary.weekStart).toISOString().split('T')[0]}.md`;

  return {
    filename,
    content,
    mimeType: 'text/markdown',
  };
}

/**
 * Export custom date range report
 */
export async function exportCustomRangeMarkdown(startDate: Date, endDate: Date, orgId?: number | null): Promise<ExportedReport> {
  // For now, use weekly summary logic
  const summary = await analytics.getWeeklySummary(startDate, orgId);
  
  const startStr = startDate.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });
  
  const endStr = endDate.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  const content = `
# OmniScope Custom Intelligence Report
**${startStr} - ${endStr}**

---

## Overview

- **Total Meetings:** ${summary.meetingCount}
- **Unique Participants:** ${summary.uniqueParticipants}
- **Unique Organizations:** ${summary.uniqueOrganizations}
- **Tasks Created:** ${summary.tasksCreated}
- **Tasks Completed:** ${summary.tasksCompleted}

---

## Top Sectors

${summary.topSectors.length > 0 ? summary.topSectors.map(s => `- **${s.sector}:** ${s.count} meetings`).join('\n') : '_No sector data available_'}

## Top Jurisdictions

${summary.topJurisdictions.length > 0 ? summary.topJurisdictions.map(j => `- **${j.jurisdiction}:** ${j.count} meetings`).join('\n') : '_No jurisdiction data available_'}

---

## Key Opportunities

${summary.keyOpportunities.length > 0 ? summary.keyOpportunities.map((o, i) => `${i + 1}. ${o}`).join('\n') : '_No opportunities recorded in this period._'}

---

## Risk Considerations

${summary.keyRisks.length > 0 ? summary.keyRisks.map((r, i) => `${i + 1}. ${r}`).join('\n') : '_No risks recorded in this period._'}

---

*Generated by OmniScope Intelligence Portal*  
*All Markets. One Scope.*
  `.trim();

  const filename = `omniscope-custom-${startDate.toISOString().split('T')[0]}-to-${endDate.toISOString().split('T')[0]}.md`;

  return {
    filename,
    content,
    mimeType: 'text/markdown',
  };
}
